CREATE TABLE public."Cell411Alert" (
    "objectId" text NOT NULL,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone,
    "targetMembers" jsonb,
    "additionalNote" text,
    "alertType" text,
    "issuedBy" text,
    location point,
    "issuerFirstName" text,
    "issuerId" text,
    "entryFor" text,
    "to" text,
    status text,
    "isGlobal" double precision,
    photo text,
    "dispatchMode" double precision,
    "forwardedToMembers" jsonb,
    "cellId" text,
    "cellName" text,
    "forwardedAlert" text,
    "forwardedBy" text,
    city text,
    country text,
    "fullAddress" text,
    audience jsonb,
    "alertId" double precision,
    "totalAudienceAU" double precision,
    "totalAudienceNAU" double precision,
    "audienceNAU" jsonb,
    "totalPatrolUsers" double precision,
    "targetNAUMembers" jsonb,
    _rperm text[],
    _wperm text[]
);
