test:
	bash getUserData.sh

all:
	bash signup.sh

testFirebase:
	bash testFirebase.sh | tee testFirebase.sh.out

testFirebase:
	bash testFirebase.sh | tee testFirebase.sh.out

login:
	bash login.sh

proc_session:
	node proc_session.js

clean:
	rm -f key.sh *.out *.json

run_REST:
	node REST.js 2>&1 | tee REST.js.out
